### ISSUE TITLE
Sapper server code minification

### ISSUE THREAD

**Issue by tommywalkie** [tommywalkie/sapper-typescript-esbuild-template#3]
Back in Sapper `0.28.0` ([#9eb4d43](https://github.com/sveltejs/sapper/commit/9eb4d43af3bf5bb4e89a7cfb21390e13c5e5fd3b)), `rollup-plugin-esbuild` was able to bundle and minify Sapper server code without issues.
When upgrading to Sapper `0.28.1` ([#9332cfc](https://github.com/sveltejs/sapper/commit/9332cfc5f33aba7682b8dbfb6e167d46e89a0364)), the following code is added on any generated Sapper server module (`src/node_modules/@sapper/server.mjs`) :

```js
function createCommonjsModule(fn, basedir, module) {
   return module = {
       path: basedir,
       exports: {},
       require: function (path, base) {
           return commonjsRequire(path, (base === undefined || base === null) ? module.path : base);
       }
   }, fn(module, module.exports), module.exports;
}
```

Which is fine, but when `rollup-plugin-esbuild` tries to minify it, it is adding **ES2020 nullish coalescing** (`a ?? b`) in `commonjsRequire(...)` second parameter which leads to `SyntaxError: Unexpected token '?'` when starting the server.

```js
function createCommonjsModule(e, t, r) {
    return r = {
        path: t,
        exports: {},
        require: function (n, o) {
            return commonjsRequire(n, o ?? r.path)
        }
    }, e(r, r.exports), r.exports
}
```

As a temporary workaround, the Rollup config will minify or not the Sapper server module based on the Sapper version.

**Comment by mrazauskas** [comment]
Is there a need to minify server side code? Take a look at the official Sapper template. `terser()` is not included in `server:` part. Only `client:` and `serviceworker:` are minified by Terser, because only these will be send over internet.

Seems like Node is supporting the nullish coalescing operator from version 14. Setting `esbuild({ target: 'node12' })` fixes the issue you have (should work with `node13` too, but I picked LTS version). The line looks like this after minification:

```javascript
return commonjsRequire(o,r==null?n.path:r)
```

By the way, I was surprised to find out that `target` in `esbuild` options is not the same as `target` in `tsconfig` file. Check [the docs](https://esbuild.github.io/api/#target).

**Comment by tommywalkie** [comment]
> Is there a need to minify server side code? Take a look at the official Sapper template. terser() is not included in server: part

Oh, that makes sense. @mrazauskas Thanks for the clue.

> By the way, I was surprised to find out that target in esbuild options is not the same as target in tsconfig file. Check the docs.

Mmmmm, unless I misunderstood the statement; this is incorrect. Here is the `target` ESBuild option value :

https://github.com/tommywalkie/sapper-typescript-esbuild-template/blob/3cffca8ec2deca541735a40d3785698be620f1aa/rollup.config.js#L20

And this is the [`target` field value](https://github.com/tsconfig/bases/blob/07882f0d30a4760cc4792ed4a78ceb3fee6ba891/bases/svelte.json#L7) in `@tsconfig/svelte` which is extending our `tsconfig` file.

```diff
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Svelte",

  "compilerOptions": {
    ...
+   "target": "es2017",
    ...
  }
}
```

FWIW, this template was mostly designed a while ago when ESBuild was only at `0.6.x`, before the new docs came out, and before the recent `0.8.x` breaking changes. There sure may be ways to improve the current setup.
