### ISSUE TITLE
Error: default.isTypeAssertionExpression is not a function (ts)

### ISSUE THREAD

**Issue by gnomeria** [tommywalkie/sapper-typescript-esbuild-template#6]
Hello. I tried to run this on `node v12.18.3` but encountered these errors. Any idea why?
```
/test-sapper-ts/src/routes/_error.svelte:NaN:1
Error: ts__default$1.default.isTypeAssertionExpression is not a function (ts)

/test-sapper-ts/src/routes/_layout.svelte:NaN:1
Error: ts__default$1.default.isTypeAssertionExpression is not a function (ts)

test-sapper-ts/src/routes/index.svelte:NaN:1
Error: ts__default$1.default.isTypeAssertionExpression is not a function (ts)
```

**Comment by tommywalkie** [comment]
Hi @gnomeria, I've tried on my side and had no issue, I'll maybe add CI though. What's your `sapper` and `svelte` versions by the way ?
```json
{
  "devDependencies": {
      "sapper": "^0.28.6",
      "svelte": "^3.24.1",
   }
}
```

**Comment by tommywalkie** [comment]
Mmmm, can confirm upgrading to `esbuild@0.8.12` did break some things but didn't get the same error logs. I'll take a look.
```bash
yarn add sapper        # ✅ yarn dev still works
yarn add svelte        # ✅ yarn dev still works
yarn add esbuild       # ❌ yarn dev breaks
```

**Comment by tommywalkie** [comment]
Ok, looks like `rollup-plugin-esbuild` doesn't support `esbuild@^0.8.0` due to a breaking change https://github.com/egoist/rollup-plugin-esbuild/pull/138.

**Comment by tommywalkie** [comment]
About your issue @gnomeria, I'm still unsure how to reproduce this but this might be relevant: https://github.com/sveltejs/language-tools/issues/685

**Comment by gnomeria** [comment]
Wow thanks for the traces ❤️ . I'll try to pin or downgrade some of the dependencies later. Cheers 👍
